// Literal per-codec facts, one row per `KvQuant` `Display` spelling.
//
// This file holds data only. `codec_facts_tests.rs` reads it with `include!`.
// Every value is a literal. Do not derive a value from the code under test:
// the table is an oracle only while it is written apart from the predicates it
// checks.

/// When `KvQuant::cpu_hot_path_reason` gives `Some`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum CpuHotPath {
    /// Never: the hot path is Metal (or plain bf16).
    Never,
    /// Always, whatever the rotor QJL switch says.
    Always,
    /// Only while the rotor QJL switch is on.
    WhenQjl,
}

/// What today's code states about one codec.
#[derive(Debug, Clone, Copy)]
#[allow(
    clippy::struct_excessive_bools,
    reason = "each bool is one predicate of today's code, written as the literal it returns"
)]
pub(crate) struct CodecFacts {
    /// `Display` spelling. The table key.
    pub(crate) spelling: &'static str,
    pub(crate) decode_reads_packed_store: bool,
    pub(crate) materialises_packed_store: bool,
    /// `feeds_bf16_k_at_decode(shares_kv)`, indexed by `shares_kv as usize`.
    pub(crate) feeds_bf16_k: [bool; 2],
    /// `feeds_bf16_v_at_decode(shares_kv)`, indexed by `shares_kv as usize`.
    pub(crate) feeds_bf16_v: [bool; 2],
    /// `carries_msl`: the codec states that it dispatches a Metal kernel.
    pub(crate) carries_msl: bool,
    pub(crate) cpu_hot_path: CpuHotPath,
    /// `approx_code_bits` as `(k, v)`.
    pub(crate) approx_code_bits: (u32, u32),
    /// `side_stores` as `(k, v)`, each store in its `Debug` text.
    pub(crate) side_stores: (Option<&'static str>, Option<&'static str>),
    pub(crate) k_below_8bit: bool,
    pub(crate) uses_mixed_path: bool,
    pub(crate) is_k_only_iso_rotor: bool,
    pub(crate) mixed_params: Option<(i32, i32, i32, i32)>,
    /// The `kv_quant` label the server writes into the metrics DB.
    pub(crate) metrics_label: &'static str,
}

pub(crate) const CODEC_FACTS: &[CodecFacts] = &[
    CodecFacts {
        spelling: "none",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: false,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (16, 16),
        side_stores: (None, None),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "none",
    },
    CodecFacts {
        spelling: "k8v4",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 4),
        side_stores: (Some("Q8"), Some("Turbo")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "k8v4",
    },
    CodecFacts {
        spelling: "k8v8",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 8),
        side_stores: (Some("Q8"), Some("Q8")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "k8v8",
    },
    CodecFacts {
        spelling: "planar",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 4),
        side_stores: (Some("Q8"), Some("Planar")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "planar",
    },
    CodecFacts {
        spelling: "planar3",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 3),
        side_stores: (Some("Q8"), Some("Planar")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "planar3",
    },
    CodecFacts {
        spelling: "planar_k",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (4, 16),
        side_stores: (Some("Planar"), None),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "planar_k",
    },
    CodecFacts {
        spelling: "mixed_k8g64_v4g64",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, true],
        feeds_bf16_v: [false, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 4),
        side_stores: (Some("Affine { group: 64 }"), Some("Affine { group: 64 }")),
        k_below_8bit: false,
        uses_mixed_path: true,
        is_k_only_iso_rotor: false,
        mixed_params: Some((8, 4, 64, 64)),
        metrics_label: "mixed",
    },
    CodecFacts {
        spelling: "rot_k_v8g64",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, true],
        feeds_bf16_v: [false, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 8),
        side_stores: (Some("Affine { group: 64 }"), Some("Affine { group: 64 }")),
        k_below_8bit: false,
        uses_mixed_path: true,
        is_k_only_iso_rotor: false,
        mixed_params: Some((8, 8, 64, 64)),
        metrics_label: "rot_k",
    },
    CodecFacts {
        spelling: "k8vturbo3",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 3),
        side_stores: (Some("Q8"), Some("Turbo")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "k8vturbo3",
    },
    CodecFacts {
        spelling: "k8vturbo3tcq",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 3),
        side_stores: (Some("Q8"), Some("Turbo")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "k8vturbo3tcq",
    },
    CodecFacts {
        spelling: "k8vturbo2",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 2),
        side_stores: (Some("Q8"), Some("Turbo")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "k8vturbo2",
    },
    CodecFacts {
        spelling: "k8vturbo2tcq",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (8, 2),
        side_stores: (Some("Q8"), Some("Turbo")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "k8vturbo2tcq",
    },
    CodecFacts {
        spelling: "tsym3",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (3, 3),
        side_stores: (Some("Turbo"), Some("Turbo")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "tsym3",
    },
    CodecFacts {
        spelling: "tsym4",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (4, 4),
        side_stores: (Some("Turbo"), Some("Turbo")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "tsym4",
    },
    CodecFacts {
        spelling: "iso3",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Always,
        approx_code_bits: (8, 3),
        side_stores: (Some("Q8"), Some("IsoBlocks")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "iso3",
    },
    CodecFacts {
        spelling: "iso4",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Always,
        approx_code_bits: (8, 4),
        side_stores: (Some("Q8"), Some("IsoBlocks")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "iso4",
    },
    CodecFacts {
        spelling: "iso3_sym",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [false, false],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (3, 3),
        side_stores: (Some("IsoRing"), Some("IsoRing")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "iso3_sym",
    },
    CodecFacts {
        spelling: "iso4_sym",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [false, false],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (4, 4),
        side_stores: (Some("IsoRing"), Some("IsoRing")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "iso4_sym",
    },
    CodecFacts {
        spelling: "k_iso3",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (3, 16),
        side_stores: (Some("IsoRing"), None),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: true,
        mixed_params: None,
        metrics_label: "k_iso3",
    },
    CodecFacts {
        spelling: "k_iso4",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Never,
        approx_code_bits: (4, 16),
        side_stores: (Some("IsoRing"), None),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: true,
        mixed_params: None,
        metrics_label: "k_iso4",
    },
    CodecFacts {
        spelling: "rotor3",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Always,
        approx_code_bits: (8, 3),
        side_stores: (Some("Q8"), Some("Rotor")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "rotor3",
    },
    CodecFacts {
        spelling: "rotor4",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Always,
        approx_code_bits: (8, 4),
        side_stores: (Some("Q8"), Some("Rotor")),
        k_below_8bit: false,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "rotor4",
    },
    CodecFacts {
        spelling: "rotor3_sym",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [false, false],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::WhenQjl,
        approx_code_bits: (3, 3),
        side_stores: (Some("Rotor"), Some("Rotor")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "rotor3_sym",
    },
    CodecFacts {
        spelling: "rotor4_sym",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [false, false],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::WhenQjl,
        approx_code_bits: (4, 4),
        side_stores: (Some("Rotor"), Some("Rotor")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "rotor4_sym",
    },
    CodecFacts {
        spelling: "k_rotor3",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::WhenQjl,
        approx_code_bits: (3, 16),
        side_stores: (Some("Rotor"), None),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: true,
        mixed_params: None,
        metrics_label: "k_rotor3",
    },
    CodecFacts {
        spelling: "k_rotor4",
        decode_reads_packed_store: true,
        materialises_packed_store: true,
        feeds_bf16_k: [false, false],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::WhenQjl,
        approx_code_bits: (4, 16),
        side_stores: (Some("Rotor"), None),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: true,
        mixed_params: None,
        metrics_label: "k_rotor4",
    },
    CodecFacts {
        spelling: "rotor_k_3_asym_v4_g64",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Always,
        approx_code_bits: (3, 4),
        side_stores: (Some("Rotor"), Some("Turbo")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "rotor_k_3_asym_v4_g64",
    },
    CodecFacts {
        spelling: "rotor_k_4_asym_v4_g64",
        decode_reads_packed_store: false,
        materialises_packed_store: false,
        feeds_bf16_k: [true, true],
        feeds_bf16_v: [true, true],
        carries_msl: true,
        cpu_hot_path: CpuHotPath::Always,
        approx_code_bits: (4, 4),
        side_stores: (Some("Rotor"), Some("Turbo")),
        k_below_8bit: true,
        uses_mixed_path: false,
        is_k_only_iso_rotor: false,
        mixed_params: None,
        metrics_label: "rotor_k_4_asym_v4_g64",
    },
];
