//! Tests for the iso3 KV-cache CPU codec.
//!
//! # Python gold fixture
//!
//! The bit-exact quaternion fixture values were generated offline using the
//! Python script below (pure Python, no torch dependency):
//!
//! ```python
//! # scripts/gen_isoquant_fixture.py
//! # q = [1.0, 0.5, -0.3, 0.2]   (not a unit quaternion — just a test vector)
//! # v = [0.1, -0.4, 0.9, 0.6]
//! # Hamilton product from rotorquant/turboquant/isoquant.py::quat_multiply
//! q = [1.0, 0.5, -0.3, 0.2]
//! v = [0.1, -0.4, 0.9, 0.6]
//! aw, ax, ay, az = q
//! bw, bx, by, bz = v
//! rw = aw*bw - ax*bx - ay*by - az*bz  # 0.45
//! rx = aw*bx + ax*bw + ay*bz - az*by  # -0.71
//! ry = aw*by - ax*bz + ay*bw + az*bx  # 0.49
//! rz = aw*bz + ax*by - ay*bx + az*bw  # 0.95
//! print(rw, rx, ry, rz)
//! # Output: 0.45 -0.71 0.49 0.95
//! ```
//!
//! Verified: Python float64 outputs match f32 within 1e-6 for these clean
//! rational inputs. The Rust test pins against the exact analytical values.

use crate::isoquant::{
    iso_decode_fast, iso_encode_fast, quat_conjugate, quat_multiply, IsoQuantError, FIXED_QUAT,
};
use crate::test_utils::{cosine_similarity_per_row, lcg_data, TEST_SEED};

// ── Bit-exact quaternion fixture ─────────────────────────────────────────────

/// Verify `quat_multiply` matches Python `isoquant.py::quat_multiply` to f32 precision.
///
/// Gold values generated by `scripts/gen_isoquant_fixture.py` (see module doc).
/// Inputs are clean rational values chosen so that Python float64 and Rust f32
/// intermediate results agree to better than 1e-6.
///
/// Python output (float64): `rw=0.45, rx=-0.71, ry=0.49, rz=0.95`
/// All four values are exact rational multiples with no f64→f32 rounding error
/// at these magnitudes.
#[test]
fn quaternion_hamilton_matches_python_bit_exact() {
    // q = [1.0, 0.5, -0.3, 0.2], v = [0.1, -0.4, 0.9, 0.6]
    // Not unit quaternions — just selected for clean arithmetic.
    let q = [1.0_f32, 0.5, -0.3, 0.2];
    let v = [0.1_f32, -0.4, 0.9, 0.6];

    let r = quat_multiply(q, v);

    // Gold values (Python script output pinned):
    // rw = aw*bw - ax*bx - ay*by - az*bz = 1.0*0.1 - 0.5*(-0.4) - (-0.3)*0.9 - 0.2*0.6
    //    = 0.1 + 0.2 + 0.27 - 0.12 = 0.45
    // rx = aw*bx + ax*bw + ay*bz - az*by = 1.0*(-0.4) + 0.5*0.1 + (-0.3)*0.6 - 0.2*0.9
    //    = -0.4 + 0.05 - 0.18 - 0.18 = -0.71
    // ry = aw*by - ax*bz + ay*bw + az*bx = 1.0*0.9 - 0.5*0.6 + (-0.3)*0.1 + 0.2*(-0.4)
    //    = 0.9 - 0.3 - 0.03 - 0.08 = 0.49
    // rz = aw*bz + ax*by - ay*bx + az*bw = 1.0*0.6 + 0.5*0.9 - (-0.3)*(-0.4) + 0.2*0.1
    //    = 0.6 + 0.45 - 0.12 + 0.02 = 0.95
    let expected = [0.45_f32, -0.71, 0.49, 0.95];
    let tol = 1e-6_f32; // tighter than 1e-5; f32 epsilon for these values is ~5e-8

    for (i, (&got, &exp)) in r.iter().zip(expected.iter()).enumerate() {
        assert!(
            (got - exp).abs() < tol,
            "component {i}: got {got:.10e}, expected {exp:.10e}, diff {:.2e} > tol {tol:.2e}",
            (got - exp).abs()
        );
    }
}

// ── Determinism gate ──────────────────────────────────────────────────────────

/// Encode → decode → encode again; assert codes are bit-identical between passes.
///
/// This verifies that `iso_encode_fast` is purely deterministic: no hidden RNG,
/// no mutable state, identical output for identical input.
#[test]
fn iso_encode_decode_roundtrip_determinism() {
    let head_dim = 64;
    let group_size = 4;
    let bits = 3;
    let n_tokens = 8;

    let data = lcg_data(n_tokens * head_dim, TEST_SEED);

    // First encode.
    let (codes1, scales1, quats1, norms1) =
        iso_encode_fast(&data, head_dim, group_size, bits).unwrap();

    // Decode.
    let decoded = iso_decode_fast(
        &codes1, &scales1, &quats1, &norms1, head_dim, group_size, bits,
    )
    .unwrap();

    // Second encode of decoded output.
    let (codes2, _scales2, _quats2, _norms2) =
        iso_encode_fast(&decoded, head_dim, group_size, bits).unwrap();

    // Codes must be bit-identical (determinism gate).
    assert_eq!(
        codes1.len(),
        codes2.len(),
        "codes length mismatch between passes"
    );
    for (i, (&c1, &c2)) in codes1.iter().zip(codes2.iter()).enumerate() {
        assert_eq!(
            c1, c2,
            "codes differ at word {i}: first pass {c1:#010x} vs second pass {c2:#010x}"
        );
    }
}

// ── head_dim guard ────────────────────────────────────────────────────────────

/// `head_dim` that is not a multiple of 4 must return `HeadDimNotMultipleOf4`.
#[test]
fn iso_head_dim_not_mod4_returns_error() {
    let data = vec![0.0_f32; 63]; // head_dim=63, 1 token
    let result = iso_encode_fast(&data, 63, 4, 3);
    match result {
        Err(IsoQuantError::HeadDimNotMultipleOf4 { head_dim: 63 }) => {} // expected
        other => panic!("expected HeadDimNotMultipleOf4(63), got {other:?}"),
    }
}

// ── group_size divisibility guard ────────────────────────────────────────────

/// `group_size` that does not divide `head_dim` must return `GroupSizeNotDivisorOfHeadDim`.
///
/// Example: head_dim=64, group_size=24 → 64 % 24 = 16 ≠ 0.
/// Without this guard, n_groups = 64/24 = 2 (truncated), leaving 16 elements
/// silently unquantized and returning under-sized output buffers as success.
#[test]
fn iso_encode_invalid_group_size_returns_err() {
    // head_dim=64, group_size=24: 24 divides by 4 (valid multiple-of-4) but
    // 64 % 24 = 16 ≠ 0 — not a divisor of head_dim.
    let head_dim = 64_usize;
    let group_size = 24_usize;
    let data = vec![0.0_f32; head_dim]; // 1 token
    let result = iso_encode_fast(&data, head_dim, group_size, 3);
    match result {
        Err(IsoQuantError::GroupSizeNotDivisorOfHeadDim {
            group_size: 24,
            head_dim: 64,
        }) => {} // expected
        other => panic!(
            "expected GroupSizeNotDivisorOfHeadDim(group_size=24, head_dim=64), got {other:?}"
        ),
    }
}

// ── Cosine gate ───────────────────────────────────────────────────────────────

/// iso3 cosine-similarity gate on LCG fixture data.
///
/// Setup: 32 tokens × 128-dim, group_size=4, bits=3.
/// LCG seed: `TEST_SEED` (pinned; must stay reproducible).
///
/// Measured cosine (first run, LCG fixture, Gaussian Lloyd codebook):
///   mean = 0.9941, min = 0.9932
///
/// Threshold is set at `measured_mean − 0.001` to guard against regression.
///
/// # Gap vs mtq published benchmark
///
/// The Python mtq reference reports cosine ≈ 0.9783 for iso3 on realistic KV
/// vectors from calibrated Llama-3 layers. Our LCG fixture yields higher cosine
/// (0.9941 mean) because:
///
///   1. LCG data has lower dynamic range than real KV activations.
///   2. rMLX uses `group_size=4` (one quaternion block per group) vs mtq's
///      larger group sizes; smaller groups give finer-grained scales.
///
/// These are different measurement conditions — the comparison is informational
/// only. Regression is gated against the measured LCG value, not vs mtq.
///
/// # Codebook divergence note
///
/// Python reference (rotorquant + mtq) uses Beta Lloyd-Max optimal codebook.
/// rMLX uses Gaussian Lloyd-Max (N(0,1)) from `turboquant::lloyd_gaussian_codebook(3)`.
/// For head_dim ≥ 64 the distributions converge; the quality gap is negligible
/// on LCG fixture and measured below the −0.001 regression margin.
#[test]
fn iso3_cosine_gate() {
    let n_tokens = 32;
    let head_dim = 128;
    let group_size = 4;
    let bits = 3;

    let data = lcg_data(n_tokens * head_dim, TEST_SEED);

    let (codes, scales, quats, norms) = iso_encode_fast(&data, head_dim, group_size, bits).unwrap();
    let decoded =
        iso_decode_fast(&codes, &scales, &quats, &norms, head_dim, group_size, bits).unwrap();

    let stats = cosine_similarity_per_row(&data, &decoded, head_dim);

    // Threshold = measured_mean − 0.001 (empirical floor).
    // Measured on first run: mean = 0.9941, min = 0.9932.
    // Update these constants if the codebook or algorithm changes (bump the
    // measured values and re-set threshold = new_mean - 0.001).
    let threshold_mean = 0.993_0_f32;
    let threshold_min = 0.992_0_f32;

    assert!(
        stats.mean >= threshold_mean,
        "iso3 cosine mean {:.6} fell below threshold {threshold_mean:.6} (n_rows={})",
        stats.mean,
        stats.n_rows,
    );
    assert!(
        stats.min >= threshold_min,
        "iso3 cosine min {:.6} fell below threshold {threshold_min:.6} (n_rows={})",
        stats.min,
        stats.n_rows,
    );

    // Diagnostic: print so the measured value appears in `cargo test -- --nocapture`
    println!(
        "iso3 cosine: mean={:.6}, min={:.6}, n_rows={} (threshold mean>={threshold_mean:.6}, min>={threshold_min:.6})",
        stats.mean, stats.min, stats.n_rows,
    );
}

// ── iso4 cosine gate ──────────────────────────────────────────────────────────

/// iso4 cosine-similarity gate on the LCG fixture.
///
/// Setup: 32 tokens × 128-dim, group_size=4, bits=4.
/// LCG seed: [`TEST_SEED`] (pinned; must stay reproducible).
///
/// Threshold: published mtq number is 0.9951 (multi-turboquant
/// `iso4`). The rMLX measurement on the LCG fixture is recorded by the test
/// itself (`println!`); the assertion uses the empirical-floor pattern from
/// `iso3_cosine_gate` — `measured_mean − 0.001` — to guard against regression
/// without coupling to the Beta-codebook published value.
///
/// rMLX uses Gaussian Lloyd-Max codebook (`lloyd_gaussian_codebook(4)`); the
/// Python reference uses Beta Lloyd-Max. The expected delta is negligible for
/// `head_dim ≥ 64` (Beta(d) → N(0, 1/d) for large d).
#[test]
fn iso4_cosine_gate() {
    let n_tokens = 32;
    let head_dim = 128;
    let group_size = 4;
    let bits = 4;

    let data = lcg_data(n_tokens * head_dim, TEST_SEED);

    let (codes, scales, quats, norms) = iso_encode_fast(&data, head_dim, group_size, bits).unwrap();
    let decoded =
        iso_decode_fast(&codes, &scales, &quats, &norms, head_dim, group_size, bits).unwrap();

    let stats = cosine_similarity_per_row(&data, &decoded, head_dim);

    // Measured on LCG fixture (TEST_SEED, n_tokens=32, head_dim=128):
    //   mean = 0.9986, min = 0.9981
    // Threshold = measured − 0.001 (regression margin, same pattern as
    // `iso3_cosine_gate`). Update both numbers if the
    // codebook or algorithm changes.
    //
    // The published Beta-codebook mtq iso4 number is 0.9951; rMLX's
    // Gaussian-codebook LCG measurement exceeds it, consistent with the
    // distributional convergence noted in the module-level docs.
    let threshold_mean = 0.997_5_f32;
    let threshold_min = 0.997_0_f32;

    assert!(
        stats.mean >= threshold_mean,
        "iso4 cosine mean {:.6} fell below threshold {threshold_mean:.6} (n_rows={})",
        stats.mean,
        stats.n_rows,
    );
    assert!(
        stats.min >= threshold_min,
        "iso4 cosine min {:.6} fell below threshold {threshold_min:.6} (n_rows={})",
        stats.min,
        stats.n_rows,
    );

    println!(
        "iso4 cosine: mean={:.6}, min={:.6}, n_rows={} (threshold mean>={threshold_mean:.6}, min>={threshold_min:.6})",
        stats.mean, stats.min, stats.n_rows,
    );
}

/// iso4 determinism: encode → decode → encode again; codes bit-identical.
///
/// Mirror of `iso_encode_decode_roundtrip_determinism` for `bits=4`. Verifies
/// the parameterized packer is purely deterministic at 4-bit width too.
#[test]
fn iso4_encode_decode_roundtrip_determinism() {
    let head_dim = 64;
    let group_size = 4;
    let bits = 4;
    let n_tokens = 8;

    let data = lcg_data(n_tokens * head_dim, TEST_SEED);

    let (codes1, scales1, quats1, norms1) =
        iso_encode_fast(&data, head_dim, group_size, bits).unwrap();

    let decoded = iso_decode_fast(
        &codes1, &scales1, &quats1, &norms1, head_dim, group_size, bits,
    )
    .unwrap();

    let (codes2, _scales2, _quats2, _norms2) =
        iso_encode_fast(&decoded, head_dim, group_size, bits).unwrap();

    assert_eq!(codes1.len(), codes2.len(), "codes length mismatch");
    for (i, (&c1, &c2)) in codes1.iter().zip(codes2.iter()).enumerate() {
        assert_eq!(
            c1, c2,
            "codes differ at word {i}: first pass {c1:#010x} vs second pass {c2:#010x}"
        );
    }
}

/// iso4 head_dim guard — head_dim not divisible by 4 must error.
#[test]
fn iso4_head_dim_not_mod4_returns_error() {
    let data = vec![0.0_f32; 63];
    let result = iso_encode_fast(&data, 63, 4, 4);
    match result {
        Err(IsoQuantError::HeadDimNotMultipleOf4 { head_dim: 63 }) => {} // expected
        other => panic!("expected HeadDimNotMultipleOf4(63), got {other:?}"),
    }
}

/// bits=5 / bits=2 / bits=0 must all be rejected by the parameterized codec.
#[test]
fn iso_unsupported_bits_rejected() {
    let data = vec![0.0_f32; 64];
    for bad_bits in [0u8, 1, 2, 5, 6, 7, 8] {
        let result = iso_encode_fast(&data, 64, 4, bad_bits);
        match result {
            Err(IsoQuantError::UnsupportedBits { bits }) if bits == bad_bits => {}
            other => panic!("expected UnsupportedBits({bad_bits}), got {other:?}"),
        }
    }
}

// ── Quaternion conjugate sanity ───────────────────────────────────────────────

/// `q * q̄ = (1, 0, 0, 0)` for a unit quaternion (within f32 tolerance).
#[test]
fn quat_conjugate_times_self_is_identity() {
    let q = FIXED_QUAT;
    let q_conj = quat_conjugate(q);
    let result = quat_multiply(q, q_conj);
    // Should be very close to (1, 0, 0, 0)
    assert!(
        (result[0] - 1.0).abs() < 1e-6,
        "w component should be ~1.0, got {}",
        result[0]
    );
    for &v in &result[1..] {
        assert!(v.abs() < 1e-6, "imaginary component should be ~0, got {v}");
    }
}

/// The fixed quaternion must be unit-length (within f32 tolerance).
#[test]
fn fixed_quat_is_unit_length() {
    let q = FIXED_QUAT;
    let norm_sq: f32 = q.iter().map(|&x| x * x).sum();
    assert!(
        (norm_sq - 1.0).abs() < 1e-5,
        "FIXED_QUAT norm_sq={norm_sq:.8} should be ~1.0"
    );
}
