#!/usr/bin/env python3
"""Generate Lloyd-Max optimal N(0,1) centroids for TurboQuant codebook.

2026-05-11: Replaces the prior N(0,1) quantile centroids with
true Lloyd-Max MSE-optimal centroids for the standard normal distribution.

Source algorithm: turboquant_plus/turboquant/codebook.py::_lloyds_gaussian
with sigma=1.0, n_iter=100.

Usage:
    python3 scripts/gen_lloyd_codebook.py

Output: Rust and MSL literals for turboquant.rs and turboquant_msl.rs.

Requirements: numpy, scipy (pip install numpy scipy).
"""

import struct
import sys


def _gaussian_conditional_expectation(sigma, a, b):
    """E[X | a < X < b] where X ~ N(0, sigma^2)."""
    from scipy import stats
    import math
    a_std = a / sigma if math.isfinite(a) else a
    b_std = b / sigma if math.isfinite(b) else b
    if not math.isfinite(a_std):
        prob = stats.norm.cdf(b_std)
    elif not math.isfinite(b_std):
        prob = stats.norm.sf(a_std)
    else:
        prob = stats.norm.cdf(b_std) - stats.norm.cdf(a_std)
    if prob < 1e-15:
        if math.isfinite(a) and not math.isfinite(b):
            return a + sigma
        elif not math.isfinite(a) and math.isfinite(b):
            return b - sigma
        elif math.isfinite(a) and math.isfinite(b):
            return (a + b) / 2.0
        else:
            return 0.0
    pdf_diff = stats.norm.pdf(a_std) - stats.norm.pdf(b_std)
    return sigma * pdf_diff / prob


def lloyds_gaussian(n_centroids, sigma=1.0, n_iter=100):
    """Lloyd's algorithm for optimal scalar quantization of N(0, sigma^2)."""
    import numpy as np
    from scipy import stats
    boundaries = stats.norm.ppf(
        np.linspace(0, 1, n_centroids + 1)[1:-1], scale=sigma
    )
    centroids = np.zeros(n_centroids)
    centroids[0] = _gaussian_conditional_expectation(sigma, float('-inf'), float(boundaries[0]))
    for i in range(1, n_centroids - 1):
        centroids[i] = _gaussian_conditional_expectation(sigma, float(boundaries[i - 1]), float(boundaries[i]))
    centroids[-1] = _gaussian_conditional_expectation(sigma, float(boundaries[-1]), float('inf'))
    for _ in range(n_iter):
        boundaries = (centroids[:-1] + centroids[1:]) / 2.0
        centroids[0] = _gaussian_conditional_expectation(sigma, float('-inf'), float(boundaries[0]))
        for i in range(1, n_centroids - 1):
            centroids[i] = _gaussian_conditional_expectation(sigma, float(boundaries[i - 1]), float(boundaries[i]))
        centroids[-1] = _gaussian_conditional_expectation(sigma, float(boundaries[-1]), float('inf'))
    return np.sort(centroids).astype('float32')


def f32_hex_msl(v):
    """IEEE-754 f32 as MSL as_type<float>(0xXXXXXXXXu) literal."""
    packed = struct.pack('>f', float(v))
    return f'as_type<float>(0x{packed.hex().upper()}u)'


def f32_rust(v):
    """f32 as Rust literal."""
    return f'{float(v):.7f}'


def main():
    try:
        import numpy as np
    except ImportError:
        print("ERROR: numpy not found. Install with: pip install numpy scipy", file=sys.stderr)
        sys.exit(1)

    print("# Lloyd-Max N(0,1) codebook — generated by gen_lloyd_codebook.py")
    print("# sigma=1.0, n_iter=100, output=f32")
    print()

    for bits in [1, 2, 3, 4]:
        n = 1 << bits
        c = lloyds_gaussian(n, sigma=1.0, n_iter=100)
        bounds = ((c[:-1] + c[1:]) / 2.0).astype('float32')

        print(f"## bits={bits} ({n} centroids, {n-1} boundaries)")
        print(f"## max_centroid = {float(c.max()):.7f}")
        print()

        # Rust literal
        vals = ', '.join(f32_rust(v) for v in c)
        print(f"# Rust CODEBOOK_{bits}BIT:")
        print(f"const CODEBOOK_{bits}BIT: [f32; {n}] = [{vals}];")
        print()

        # MSL CB literal
        print(f"# MSL CB[{n}]:")
        print("constant float CB[" + str(n) + "] = {")
        for i, v in enumerate(c):
            comma = "," if i < n - 1 else ""
            print(f"    {f32_hex_msl(v)}{comma}  // {float(v):+.7f}")
        print("};")
        print()

        # MSL BOUNDARIES literal
        print(f"# MSL BOUNDARIES[{n-1}]:")
        print("constant float BOUNDARIES[" + str(n-1) + "] = {")
        for i, v in enumerate(bounds):
            comma = "," if i < n - 2 else ""
            print(f"    {f32_hex_msl(v)}{comma}  // {float(v):+.7f}")
        print("};")
        print()
        print("---")
        print()


if __name__ == "__main__":
    main()
