//! DFlash 2 forward tests.
//!
//! Two oracles, because neither alone is enough.
//!
//! * **Analytic.** The convolution is applied to hand-built weights whose
//!   answer is a closed form written out in the test. This is what pins the
//!   things a plausible-looking hidden state hides: which tap reads the
//!   previous position, that the tap reaching before the block reads zero, that
//!   the base term is per channel while the correction is per group, and that
//!   one projection carries both sides in that order.
//! * **The reference implementation.** `tests/fixtures/dflash2_scale` holds a
//!   small synthetic drafter snapshot and the hidden states the z-lab MLX
//!   reference produces from it, for three shapes of input. It is generated by
//!   the `generate.py` beside it. This is what pins the whole stack — the
//!   conditioning projection, the norms, RoPE, the sliding mask and the MLP —
//!   against something other than this port's own opinion.
//!
//! Everything here runs on the CPU device and needs no model snapshot, so it
//! runs under `make test` rather than only where a checkpoint happens to be.

use std::path::{Path, PathBuf};

use rmlx_mlx::Dtype;

use super::*;
use crate::layers::Linear;

/// Where the reference snapshot and its expected outputs live.
const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/dflash2_scale");

/// The scale model's width, matching the fixture's `config.json`.
const SCALE_HIDDEN: usize = 64;

/// Largest absolute difference from the reference this port is allowed: one
/// bf16 unit in the last place at the magnitude these hidden states reach.
///
/// Both sides run the same MLX ops in bf16 on the same device, so the only
/// difference left is rounding — the reference masks with a boolean where this
/// port adds a large-negative bias, and it rotates its conditioning rows at the
/// drafter cache's absolute offset where this port rotates them from zero. All
/// three cases land exactly here and no further; the reference's own answer
/// moves by the same one place between two absolute offsets that are
/// mathematically identical. The cases are 0.60 apart, ~37x this bound.
const REFERENCE_TOL: f32 = 0.016;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

#[allow(
    clippy::expect_used,
    reason = "test helper: an array that cannot be materialised is the assertion failing"
)]
fn to_f32(a: &Array) -> Vec<f32> {
    let f = a
        .astype(Dtype::F32, Device::Cpu)
        .expect("cast to f32 for comparison");
    f.eval().expect("eval");
    f.to_bytes()
        .expect("read bytes")
        .chunks_exact(4)
        .map(|c| {
            let mut b = [0u8; 4];
            b.copy_from_slice(c);
            f32::from_le_bytes(b)
        })
        .collect()
}

#[allow(
    clippy::expect_used,
    reason = "test helper: a shape that does not match the data it is given is the assertion failing"
)]
fn f32_array(values: &[f32], shape: &[i32]) -> Array {
    Array::from_f32_slice(values, shape).expect("build test array")
}

/// Largest absolute difference between two equally-shaped arrays.
fn max_abs_diff(a: &Array, b: &Array) -> f32 {
    let (x, y) = (to_f32(a), to_f32(b));
    assert_eq!(
        x.len(),
        y.len(),
        "compared arrays must have the same length"
    );
    x.iter()
        .zip(&y)
        .map(|(p, q)| (p - q).abs())
        .fold(0.0f32, f32::max)
}

/// Read one tensor out of a safetensors file into an [`Array`].
#[allow(
    clippy::expect_used,
    reason = "test helper: a committed fixture that does not parse is the assertion failing"
)]
fn fixture_tensor(file: &Path, name: &str) -> Array {
    let bytes = std::fs::read(file).expect("fixture file is readable");
    let st = safetensors::SafeTensors::deserialize(&bytes).expect("fixture parses");
    let t = st.tensor(name).expect("fixture carries the tensor");
    let view = rmlx_loader::TensorView {
        name,
        dtype: t.dtype(),
        shape: t.shape().to_vec(),
        bytes: t.data(),
    };
    Array::from_safetensor_view(&view).expect("tensor loads")
}

fn reference_file() -> PathBuf {
    Path::new(FIXTURE).join("reference.safetensors")
}

/// Load the fixture drafter, optionally re-writing `sliding_window` first.
///
/// A different window is a different config over the same weights, so the
/// snapshot is copied into a temp dir rather than duplicated in the fixture.
#[allow(
    clippy::expect_used,
    reason = "test helper: a committed fixture that will not load is the assertion failing"
)]
fn scale_drafter(sliding_window: Option<u64>) -> (DFlash2Drafter, Option<tempfile::TempDir>) {
    let Some(window) = sliding_window else {
        let d = DFlash2Drafter::load(Path::new(FIXTURE), SCALE_HIDDEN, Device::Cpu)
            .expect("the fixture snapshot loads");
        return (d, None);
    };
    let dir = tempfile::tempdir().expect("temp dir");
    let text = std::fs::read_to_string(Path::new(FIXTURE).join("config.json"))
        .expect("fixture config is readable");
    let mut cfg: serde_json::Value = serde_json::from_str(&text).expect("fixture config parses");
    cfg.as_object_mut()
        .expect("config is an object")
        .insert("sliding_window".to_owned(), serde_json::json!(window));
    std::fs::write(dir.path().join("config.json"), cfg.to_string()).expect("write config");
    std::fs::copy(
        Path::new(FIXTURE).join("model.safetensors"),
        dir.path().join("model.safetensors"),
    )
    .expect("copy weights");
    let d = DFlash2Drafter::load(dir.path(), SCALE_HIDDEN, Device::Cpu)
        .expect("the fixture snapshot loads at another window");
    (d, Some(dir))
}

// ---------------------------------------------------------------------------
// the convolution, against a closed form
// ---------------------------------------------------------------------------

/// The fixture drafter's convolution shape, so the closed form below is checked
/// at the width and grouping the loader actually produces.
const CONV_HIDDEN: usize = SCALE_HIDDEN;
/// Channels sharing one kernel correction, from the fixture's config.
const CONV_GROUP: usize = 16;
/// Corrections per position, per tap.
const CONV_GROUPS: usize = CONV_HIDDEN / CONV_GROUP;
/// Taps this drafter convolves.
const CONV_TAPS: usize = 2;
/// Block positions the closed form covers — enough that a tap reaching before
/// the block and a tap reaching inside it both occur.
const CONV_LEN: usize = 3;

/// The block this section convolves, `x[t][c]`, distinct in both axes.
fn conv_x() -> Vec<f32> {
    (0..CONV_LEN * CONV_HIDDEN)
        .map(|i| (i as f32) * 0.125 - 6.0)
        .collect()
}

/// `base[side][tap][channel]`, distinct in all three axes: reading the wrong
/// side, the wrong tap or the wrong channel gives a different answer.
fn conv_base() -> Vec<f32> {
    (0..2 * CONV_TAPS * CONV_HIDDEN)
        .map(|i| 0.5 - (i as f32) * 0.01)
        .collect()
}

/// One side of [`conv_base`], `[tap][channel]`.
#[allow(
    clippy::indexing_slicing,
    reason = "test fixture: every buffer is sized from the same constants the index is computed from, so an out-of-range index is the harness failing"
)]
fn base_side(base: &[f32], side: usize) -> Vec<f32> {
    base[side * CONV_TAPS * CONV_HIDDEN..(side + 1) * CONV_TAPS * CONV_HIDDEN].to_vec()
}

/// `correction[t][tap][group]`, distinct in all three axes.
fn conv_correction() -> Vec<f32> {
    (0..CONV_LEN * CONV_TAPS * CONV_GROUPS)
        .map(|i| ((i % 7) as f32) * 0.25 - 0.75 + (i as f32) * 0.03)
        .collect()
}

/// The closed form this section checks against:
/// `out[t][c] = SUM_k (base[k][c] + correction[t][k][c / group]) * x[t - k][c]`,
/// with `x[-1] = 0`.
///
/// `base` is one side, `[tap][channel]`; `correction` is `[t][tap][group]`.
#[allow(
    clippy::indexing_slicing,
    reason = "test fixture: every buffer is sized from the same constants the index is computed from, so an out-of-range index is the harness failing"
)]
fn expected_convolution(base: &[f32], correction: &[f32], x: &[f32]) -> Vec<f32> {
    let mut out = vec![0.0f32; CONV_LEN * CONV_HIDDEN];
    for t in 0..CONV_LEN {
        for c in 0..CONV_HIDDEN {
            let mut acc = 0.0;
            for tap in 0..CONV_TAPS {
                if tap > t {
                    continue;
                }
                let k = base[tap * CONV_HIDDEN + c]
                    + correction[(t * CONV_TAPS + tap) * CONV_GROUPS + c / CONV_GROUP];
                acc += k * x[(t - tap) * CONV_HIDDEN + c];
            }
            out[t * CONV_HIDDEN + c] = acc;
        }
    }
    out
}

/// A convolution carrying the given base kernel and projection weight.
fn conv_with(base: &[f32], projection: &[f32]) -> DFlash2Conv {
    let rows = (2 * CONV_TAPS * CONV_GROUPS) as i32;
    DFlash2Conv {
        base_kernel: f32_array(base, &[2, CONV_TAPS as i32, CONV_HIDDEN as i32]),
        kernel_projection: Linear::Plain {
            weight: f32_array(projection, &[rows, CONV_HIDDEN as i32]),
        },
    }
}

fn conv_x_array(x: &[f32]) -> Array {
    f32_array(x, &[1, CONV_LEN as i32, CONV_HIDDEN as i32])
}

fn correction_array(correction: &[f32]) -> Array {
    f32_array(
        correction,
        &[1, CONV_LEN as i32, CONV_TAPS as i32, CONV_GROUPS as i32],
    )
}

/// Tap 0 multiplies this position, tap 1 the one before it, and the tap that
/// reaches before the block reads zero rather than wrapping to its end.
///
/// The correction is zero here, so only the per-channel base term is in play,
/// and each side is checked against its own half of the base kernel — a port
/// reading the other side fails the other assertion.
#[test]
fn a_two_tap_convolution_reads_this_position_and_the_one_before_it() {
    let (drafter, _dir) = scale_drafter(None);
    let base = conv_base();
    let x = conv_x();
    let zero_correction = vec![0.0f32; CONV_LEN * CONV_TAPS * CONV_GROUPS];
    let conv = conv_with(&base, &vec![0.0; 2 * CONV_TAPS * CONV_GROUPS * CONV_HIDDEN]);
    let correction = correction_array(&zero_correction);

    for side in [ConvSide::Prepare, ConvSide::Finish] {
        let got = match drafter.convolve(&conv, &conv_x_array(&x), &correction, side) {
            Ok(a) => a,
            Err(e) => panic!("convolve: {e}"),
        };
        assert_eq!(got.shape(), vec![1, CONV_LEN as i32, CONV_HIDDEN as i32]);
        let want = expected_convolution(&base_side(&base, side as usize), &zero_correction, &x);
        let diff = max_abs_diff(&got, &f32_array(&want, &got.shape()));
        assert!(diff < 1e-4, "side {} differs by {diff}", side as i32);
    }
}

/// The base term is per channel and the correction per group: every channel of
/// one group takes the same correction, and no group takes another's.
#[test]
fn the_kernel_correction_is_shared_across_a_group_of_channels() {
    let (drafter, _dir) = scale_drafter(None);
    let base = conv_base();
    let x = conv_x();
    let correction = conv_correction();
    let conv = conv_with(&base, &vec![0.0; 2 * CONV_TAPS * CONV_GROUPS * CONV_HIDDEN]);

    let got = match drafter.convolve(
        &conv,
        &conv_x_array(&x),
        &correction_array(&correction),
        ConvSide::Prepare,
    ) {
        Ok(a) => a,
        Err(e) => panic!("convolve: {e}"),
    };
    let want = expected_convolution(&base_side(&base, 0), &correction, &x);
    let diff = max_abs_diff(&got, &f32_array(&want, &got.shape()));
    assert!(diff < 1e-4, "the grouped correction differs by {diff}");
}

/// The kernel projection reads the sublayer's input once and its output is laid
/// out `[side, tap, group]`: the prepare side is applied here and the finish
/// side is handed back for the sublayer's output.
#[test]
#[allow(
    clippy::indexing_slicing,
    reason = "test fixture: every buffer is sized from the same constants the index is computed from, so an out-of-range index is the harness failing"
)]
fn one_projection_of_the_input_carries_both_sides_of_the_kernel() {
    let (drafter, _dir) = scale_drafter(None);
    let x = conv_x();
    let rows = 2 * CONV_TAPS * CONV_GROUPS;
    // Row r reads channel 0 only, scaled by r + 1 — so the projection output at
    // position t is (1..=rows) * x[t][0] and every slot of it is distinct.
    let mut projection = vec![0.0f32; rows * CONV_HIDDEN];
    for (r, row) in projection.chunks_exact_mut(CONV_HIDDEN).enumerate() {
        row[0] = (r + 1) as f32;
    }
    let conv = conv_with(&vec![0.0; 2 * CONV_TAPS * CONV_HIDDEN], &projection);

    let (prepared, finish) = match drafter.conv_prepare(&conv, &conv_x_array(&x)) {
        Ok(v) => v,
        Err(e) => panic!("conv_prepare: {e}"),
    };

    // What each side's correction must be, if the projection output is read as
    // [side, tap, group] in that order.
    let side_correction = |side: usize| -> Vec<f32> {
        let mut out = vec![0.0f32; CONV_LEN * CONV_TAPS * CONV_GROUPS];
        for t in 0..CONV_LEN {
            for tap in 0..CONV_TAPS {
                for group in 0..CONV_GROUPS {
                    let slot = side * CONV_TAPS * CONV_GROUPS + tap * CONV_GROUPS + group;
                    out[(t * CONV_TAPS + tap) * CONV_GROUPS + group] =
                        (slot + 1) as f32 * x[t * CONV_HIDDEN];
                }
            }
        }
        out
    };

    assert_eq!(
        finish.shape(),
        vec![1, CONV_LEN as i32, CONV_TAPS as i32, CONV_GROUPS as i32],
        "the finish kernel keeps the [taps, groups] shape the convolution reads"
    );
    let want_finish = side_correction(1);
    let finish_diff = max_abs_diff(&finish, &f32_array(&want_finish, &finish.shape()));
    assert!(
        finish_diff < 1e-2,
        "the finish side must be the projection's second half, off by {finish_diff}"
    );

    let want_prepared =
        expected_convolution(&vec![0.0; CONV_TAPS * CONV_HIDDEN], &side_correction(0), &x);
    let prepared_diff = max_abs_diff(&prepared, &f32_array(&want_prepared, &prepared.shape()));
    assert!(
        prepared_diff < 1e-2,
        "the prepared input must use the projection's first half, off by {prepared_diff}"
    );
}

// ---------------------------------------------------------------------------
// the whole stack, against the reference implementation
// ---------------------------------------------------------------------------

/// The three reference cases are far enough apart that matching all of them is
/// not something a forward ignoring the window or the context could do.
///
/// Without this the parity assertions below could all hold on a port that
/// silently dropped the sliding window, because the fixture would not be able
/// to tell.
#[test]
fn the_reference_cases_are_further_apart_than_the_tolerance() {
    let file = reference_file();
    let cases = ["hidden_wide", "hidden_window_trims", "hidden_short_context"];
    for (i, a) in cases.iter().enumerate() {
        for b in cases.iter().skip(i + 1) {
            let diff = max_abs_diff(&fixture_tensor(&file, a), &fixture_tensor(&file, b));
            assert!(
                diff > REFERENCE_TOL * 5.0,
                "{a} and {b} differ by only {diff}; a fixture this close cannot \
                 separate a port that ignores the window from one that does not"
            );
        }
    }
}

/// The whole stack reproduces the reference forward: the conditioning
/// projection, both convolutions per layer, attention over context and block,
/// RoPE, the MLP and the final norm.
#[test]
fn the_stack_reproduces_the_reference_forward() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden");
    let (drafter, _dir) = scale_drafter(None);

    let got = match drafter.forward_hidden(&block, &ctx) {
        Ok(a) => a,
        Err(e) => panic!("forward_hidden: {e}"),
    };
    let want = fixture_tensor(&file, "hidden_wide");
    assert_eq!(got.shape(), want.shape());
    let diff = max_abs_diff(&got, &want);
    assert!(
        diff <= REFERENCE_TOL,
        "the stack differs from the reference by {diff}"
    );
}

/// Conditioning rows older than the attention window are dropped, and the rows
/// that survive are masked exactly as far back as the window reaches.
///
/// At window 4 over 6 conditioning rows the reference keeps 3 and masks one
/// more of them per block position; a port that kept all 6, or kept 3 and
/// masked none, lands 0.6 away.
#[test]
fn the_window_drops_the_conditioning_rows_the_reference_drops() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden");
    let (drafter, _dir) = scale_drafter(Some(4));

    let got = match drafter.forward_hidden(&block, &ctx) {
        Ok(a) => a,
        Err(e) => panic!("forward_hidden: {e}"),
    };
    let diff = max_abs_diff(&got, &fixture_tensor(&file, "hidden_window_trims"));
    assert!(
        diff <= REFERENCE_TOL,
        "the windowed stack differs from the reference by {diff}"
    );
}

/// The mask is the reference's predicate, cell for cell, at a shape whose
/// positions bf16 cannot represent.
///
/// The reference decides one boolean per (query, key) pair
/// (`model_mlx.py`, `DFlashAttention.__call__`):
///
/// ```text
/// context = (key < ctx_len) & (ctx_len + t - key < sliding_window)
/// block   = key >= ctx_len
/// allowed = context | block
/// ```
///
/// Written out in integers here rather than compared against a stored tensor,
/// so it is the reference's rule being checked and not this port's output.
///
/// **The second shape, at bf16, is the point.** `ctx_len = 257` is the first
/// integer bf16 rounds — it lands on 256 — and the window is one wider than the
/// context, so the deepest block queries reach back past key 256 and the
/// `block` term is what decides it. That makes the position threshold's dtype
/// observable: casting it to the block's dtype, which is what the `f32-ok`
/// marker beside it exists to stop, opens a key the window blocks. At every
/// shape the reference fixtures use — contexts of 2, 3 and 6 — bf16 is exact
/// and the same cast changes nothing, which is why no fixture could defend that
/// marker.
///
/// The dtype is swept because the production call passes the block's, which is
/// bf16, and a check run only at `f32` would make that cast a no-op.
#[test]
#[allow(
    clippy::indexing_slicing,
    reason = "test assertion: the mask is read at the shape window_mask was asked for, and a shorter buffer than that is the assertion failing"
)]
fn the_mask_is_the_references_predicate_including_past_bf16s_integers() {
    // (sliding_window, ctx_len, block_len)
    let shapes = [(4i32, 6i32, 4i32), (258, 257, 258)];
    for ((window, ctx_len, block_len), dtype) in shapes
        .into_iter()
        .flat_map(|s| [(s, Dtype::Bf16), (s, Dtype::F32)])
    {
        let (drafter, _dir) = scale_drafter(Some(window as u64));
        let mask = match drafter.window_mask(block_len, ctx_len, dtype) {
            Ok(m) => m,
            Err(e) => panic!("window_mask({window}, {ctx_len}, {block_len}, {dtype:?}): {e}"),
        };
        let keys = ctx_len + block_len;
        assert_eq!(mask.shape(), vec![1, 1, block_len, keys]);
        let got = to_f32(&mask);
        assert_eq!(got.len(), (block_len * keys) as usize);

        let mut disagreements = 0usize;
        let mut first = String::new();
        for t in 0..block_len {
            for k in 0..keys {
                let context = k < ctx_len && ctx_len + t - k < window;
                let want_open = context || k >= ctx_len;
                let is_open = got[(t * keys + k) as usize] == 0.0;
                if is_open != want_open {
                    disagreements += 1;
                    if first.is_empty() {
                        first = format!(
                            "query {t}, key {k}: the reference {} it and the mask {} it",
                            if want_open { "opens" } else { "blocks" },
                            if is_open { "opens" } else { "blocks" },
                        );
                    }
                }
            }
        }
        assert_eq!(
            disagreements,
            0,
            "at window {window}, context {ctx_len}, block {block_len}, {dtype:?} the \
             mask disagrees with the reference on {disagreements} of {} pairs; {first}",
            block_len * keys
        );
    }
}

// ---------------------------------------------------------------------------
// the conditioning window: which rows are carried, and how many
// ---------------------------------------------------------------------------

/// The row count the trim keeps is the largest one whose oldest row any block
/// query can still read — derived from the mask's own predicate, not restated
/// from the expression that computes it.
///
/// This is the number the round loop's buffer is bounded by, and the round loop
/// cannot show it: the mask blocks whatever the trim leaves over, so keeping one
/// row too many is invisible in an answer. It is a memory bound, and this is
/// where it is checked.
#[test]
fn the_trim_keeps_every_row_a_block_query_can_reach_and_no_more() {
    for window in [2i32, 4, 5, 17, 2048] {
        let (drafter, _dir) = scale_drafter(Some(window as u64));
        // The shallowest block query sits at key position `ctx_len`, and the
        // window lets it read back to `ctx_len - window + 1`. The oldest kept
        // row is index 0, so it is readable exactly while that is <= 0.
        let readable = |ctx_len: i32| ctx_len - window < 0;
        let largest = (1..=window).rev().find(|&rows| readable(rows)).unwrap_or(0);
        assert_eq!(
            drafter.conditioning_rows(),
            largest,
            "at window {window} the deepest reachable context is {largest} rows; \
             keeping fewer discards a row the mask would have shown the drafter, \
             keeping more carries one it will always hide"
        );
        assert!(
            !readable(largest + 1),
            "at window {window} the row past the bound must be unreadable, or this \
             asserts nothing about where the bound is"
        );
    }
}

/// Rows of `[1, rows, width]` counting up from zero, one distinct value per row
/// so a trim that kept the wrong end is a different answer.
fn conditioning_rows_of(rows: i32, width: i32) -> Array {
    let data: Vec<f32> = (0..rows)
        .flat_map(|r| std::iter::repeat_n(r as f32, width as usize))
        .collect();
    f32_array(&data, &[1, rows, width])
}

/// The first element of every row, which is that row's own number.
#[allow(
    clippy::indexing_slicing,
    reason = "test assertion: the array's shape is the one the fixture gave it"
)]
fn row_numbers(a: &Array) -> Vec<i32> {
    let width = a.shape()[2] as usize;
    to_f32(a).iter().step_by(width).map(|v| *v as i32).collect()
}

/// Past the window the **newest** rows survive, and a buffer inside it is
/// carried whole.
///
/// Which end is kept is the whole property: the drafter attends over the rows
/// nearest the block, so a trim that kept the oldest would condition every round
/// on the start of the prompt and go on drafting without an error.
#[test]
fn the_trim_keeps_the_newest_rows_and_carries_a_short_buffer_whole() {
    let (drafter, _dir) = scale_drafter(Some(5));
    let keep = drafter.conditioning_rows();
    assert_eq!(keep, 4);
    let width = (drafter.cfg.target_layer_ids.len() * SCALE_HIDDEN) as i32;

    let short = match drafter.trim_conditioning(&conditioning_rows_of(3, width)) {
        Ok(a) => a,
        Err(e) => panic!("trim_conditioning: {e}"),
    };
    assert_eq!(row_numbers(&short), vec![0, 1, 2], "inside the window");

    // One row past the window: the narrowest shape the trim is observable at,
    // and the one an off-by-one in the start index moves.
    let over = match drafter.trim_conditioning(&conditioning_rows_of(5, width)) {
        Ok(a) => a,
        Err(e) => panic!("trim_conditioning: {e}"),
    };
    assert_eq!(over.shape(), vec![1, 4, width]);
    assert_eq!(row_numbers(&over), vec![1, 2, 3, 4]);

    let far = match drafter.trim_conditioning(&conditioning_rows_of(9, width)) {
        Ok(a) => a,
        Err(e) => panic!("trim_conditioning: {e}"),
    };
    assert_eq!(row_numbers(&far), vec![5, 6, 7, 8]);

    // Idempotent, which is what makes the round loop's grow-then-trim bounded
    // rather than merely bounded on its first pass.
    let again = match drafter.trim_conditioning(&far) {
        Ok(a) => a,
        Err(e) => panic!("trim_conditioning: {e}"),
    };
    assert_eq!(row_numbers(&again), vec![5, 6, 7, 8]);
}

/// Extending the carried buffer bounds it in the same step, so a buffer already
/// at the bound stays there however many rounds append to it.
///
/// The round loop's per-round growth goes through this and nothing else. Growing
/// without bounding produces the same tokens and an unbounded allocation, which
/// is why the two are one operation rather than two lines at a call site.
#[test]
fn extending_the_carried_buffer_leaves_it_at_the_bound() {
    let (drafter, _dir) = scale_drafter(Some(5));
    let keep = drafter.conditioning_rows();
    let width = (drafter.cfg.target_layer_ids.len() * SCALE_HIDDEN) as i32;

    let mut carried = conditioning_rows_of(2, width);
    let mut next = 2;
    for round in 0..6 {
        let committed = f32_array(
            &(0..3 * width)
                .map(|i| (next + i / width) as f32)
                .collect::<Vec<f32>>(),
            &[1, 3, width],
        );
        next += 3;
        carried = match drafter.extend_conditioning(&carried, &committed) {
            Ok(a) => a,
            Err(e) => panic!("extend_conditioning at round {round}: {e}"),
        };
        let rows = row_numbers(&carried);
        assert!(
            rows.len() as i32 <= keep,
            "round {round} carries {} rows past a bound of {keep}",
            rows.len()
        );
        assert_eq!(
            rows.last().copied(),
            Some(next - 1),
            "round {round} must end on the newest committed row"
        );
    }
    assert_eq!(row_numbers(&carried).len() as i32, keep, "saturated");
}

/// A conditioning buffer of another width or rank is refused rather than
/// trimmed.
///
/// The width is `len(target_layer_ids) * hidden_size`, and a capture taken at a
/// different set of target layers has the same rank and the same row count. The
/// drafter's `fc` would consume it, project it, and draft from it.
#[test]
fn a_conditioning_buffer_the_projection_cannot_read_is_refused() {
    let (drafter, _dir) = scale_drafter(None);
    let width = (drafter.cfg.target_layer_ids.len() * SCALE_HIDDEN) as i32;

    let err = match drafter.trim_conditioning(&conditioning_rows_of(4, width - SCALE_HIDDEN as i32))
    {
        Ok(a) => panic!("a narrower buffer must be refused, got {:?}", a.shape()),
        Err(e) => e.to_string(),
    };
    assert!(err.contains("not the"), "names the mismatch: {err}");
    assert!(
        err.contains(&format!("{width}")),
        "names the width it wanted: {err}"
    );

    let flat = f32_array(&[0.0, 1.0, 2.0], &[3]);
    let err = match drafter.trim_conditioning(&flat) {
        Ok(a) => panic!("a rank-1 buffer must be refused, got {:?}", a.shape()),
        Err(e) => e.to_string(),
    };
    assert!(err.contains("[3]"), "names what it got: {err}");
}

/// A conditioning context shorter than the block is the reference's answer too:
/// nothing in the mask or the position arithmetic assumes the context is the
/// longer of the two.
#[test]
fn a_context_shorter_than_the_block_matches_the_reference() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden_short");
    let (drafter, _dir) = scale_drafter(None);

    let got = match drafter.forward_hidden(&block, &ctx) {
        Ok(a) => a,
        Err(e) => panic!("forward_hidden: {e}"),
    };
    let diff = max_abs_diff(&got, &fixture_tensor(&file, "hidden_short_context"));
    assert!(
        diff <= REFERENCE_TOL,
        "a short context differs from the reference by {diff}"
    );
}

/// An input at a shape the config does not predict is refused, naming the input
/// and what was wanted.
#[test]
fn an_input_the_config_does_not_predict_is_refused() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden");
    let (drafter, _dir) = scale_drafter(None);

    // The conditioning is as wide as one target layer, not all of them — what a
    // caller that forgot to concatenate produces.
    let one_layer = match ctx.slice(&[0, 0, 0], &[1, 6, 64], &[1, 1, 1], Device::Cpu) {
        Ok(a) => a,
        Err(e) => panic!("slice: {e}"),
    };
    let err = match drafter.forward_hidden(&block, &one_layer) {
        Ok(_) => panic!("a conditioning input one layer wide must be refused"),
        Err(e) => e.to_string(),
    };
    assert!(
        err.contains("target_hidden") && err.contains("128"),
        "the refusal must name the input and the width it wanted: {err}"
    );

    // A block with no batch axis is the other shape a caller gets wrong.
    let rank_two = match block.reshape(&[4, 64], Device::Cpu) {
        Ok(a) => a,
        Err(e) => panic!("reshape: {e}"),
    };
    let err = match drafter.forward_hidden(&rank_two, &ctx) {
        Ok(_) => panic!("a rank-2 block must be refused"),
        Err(e) => e.to_string(),
    };
    assert!(
        err.contains("block") && err.contains("rank-3"),
        "the refusal must name the input and the rank it wanted: {err}"
    );
}
