//! DFlash 2 forward tests.
//!
//! Two oracles, because neither alone is enough.
//!
//! * **Analytic.** The convolution is applied to hand-built weights whose
//!   answer is a closed form written out in the test. This is what pins the
//!   things a plausible-looking hidden state hides: which tap reads the
//!   previous position, that the tap reaching before the block reads zero, that
//!   the base term is per channel while the correction is per group, and that
//!   one projection carries both sides in that order.
//! * **The reference implementation.** `tests/fixtures/dflash2_scale` holds a
//!   small synthetic drafter snapshot and the hidden states the z-lab MLX
//!   reference produces from it, for three shapes of input. It is generated by
//!   the `generate.py` beside it. This is what pins the whole stack — the
//!   conditioning projection, the norms, RoPE, the sliding mask and the MLP —
//!   against something other than this port's own opinion.
//!
//! Everything here runs on the CPU device and needs no model snapshot, so it
//! runs under `make test` rather than only where a checkpoint happens to be.

use std::path::{Path, PathBuf};

use rmlx_mlx::Dtype;

use super::*;
use crate::layers::Linear;

/// Where the reference snapshot and its expected outputs live.
const FIXTURE: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures/dflash2_scale");

/// The scale model's width, matching the fixture's `config.json`.
const SCALE_HIDDEN: usize = 64;

/// Largest absolute difference from the reference this port is allowed: one
/// bf16 unit in the last place at the magnitude these hidden states reach.
///
/// Both sides run the same MLX ops in bf16 on the same device, so the only
/// difference left is rounding — the reference masks with a boolean where this
/// port adds a large-negative bias, and it rotates its conditioning rows at the
/// drafter cache's absolute offset where this port rotates them from zero. All
/// three cases land exactly here and no further; the reference's own answer
/// moves by the same one place between two absolute offsets that are
/// mathematically identical. The cases are 0.60 apart, ~37x this bound.
const REFERENCE_TOL: f32 = 0.016;

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

#[allow(
    clippy::expect_used,
    reason = "test helper: an array that cannot be materialised is the assertion failing"
)]
fn to_f32(a: &Array) -> Vec<f32> {
    let f = a
        .astype(Dtype::F32, Device::Cpu)
        .expect("cast to f32 for comparison");
    f.eval().expect("eval");
    f.to_bytes()
        .expect("read bytes")
        .chunks_exact(4)
        .map(|c| {
            let mut b = [0u8; 4];
            b.copy_from_slice(c);
            f32::from_le_bytes(b)
        })
        .collect()
}

#[allow(
    clippy::expect_used,
    reason = "test helper: a shape that does not match the data it is given is the assertion failing"
)]
fn f32_array(values: &[f32], shape: &[i32]) -> Array {
    Array::from_f32_slice(values, shape).expect("build test array")
}

/// Largest absolute difference between two equally-shaped arrays.
fn max_abs_diff(a: &Array, b: &Array) -> f32 {
    let (x, y) = (to_f32(a), to_f32(b));
    assert_eq!(
        x.len(),
        y.len(),
        "compared arrays must have the same length"
    );
    x.iter()
        .zip(&y)
        .map(|(p, q)| (p - q).abs())
        .fold(0.0f32, f32::max)
}

/// Read one tensor out of a safetensors file into an [`Array`].
#[allow(
    clippy::expect_used,
    reason = "test helper: a committed fixture that does not parse is the assertion failing"
)]
fn fixture_tensor(file: &Path, name: &str) -> Array {
    let bytes = std::fs::read(file).expect("fixture file is readable");
    let st = safetensors::SafeTensors::deserialize(&bytes).expect("fixture parses");
    let t = st.tensor(name).expect("fixture carries the tensor");
    let view = rmlx_loader::TensorView {
        name,
        dtype: t.dtype(),
        shape: t.shape().to_vec(),
        bytes: t.data(),
    };
    Array::from_safetensor_view(&view).expect("tensor loads")
}

fn reference_file() -> PathBuf {
    Path::new(FIXTURE).join("reference.safetensors")
}

/// Load the fixture drafter, optionally re-writing `sliding_window` first.
///
/// A different window is a different config over the same weights, so the
/// snapshot is copied into a temp dir rather than duplicated in the fixture.
#[allow(
    clippy::expect_used,
    reason = "test helper: a committed fixture that will not load is the assertion failing"
)]
fn scale_drafter(sliding_window: Option<u64>) -> (DFlash2Drafter, Option<tempfile::TempDir>) {
    let Some(window) = sliding_window else {
        let d = DFlash2Drafter::load(Path::new(FIXTURE), SCALE_HIDDEN, Device::Cpu)
            .expect("the fixture snapshot loads");
        return (d, None);
    };
    let dir = tempfile::tempdir().expect("temp dir");
    let text = std::fs::read_to_string(Path::new(FIXTURE).join("config.json"))
        .expect("fixture config is readable");
    let mut cfg: serde_json::Value = serde_json::from_str(&text).expect("fixture config parses");
    cfg.as_object_mut()
        .expect("config is an object")
        .insert("sliding_window".to_owned(), serde_json::json!(window));
    std::fs::write(dir.path().join("config.json"), cfg.to_string()).expect("write config");
    std::fs::copy(
        Path::new(FIXTURE).join("model.safetensors"),
        dir.path().join("model.safetensors"),
    )
    .expect("copy weights");
    let d = DFlash2Drafter::load(dir.path(), SCALE_HIDDEN, Device::Cpu)
        .expect("the fixture snapshot loads at another window");
    (d, Some(dir))
}

// ---------------------------------------------------------------------------
// the convolution, against a closed form
// ---------------------------------------------------------------------------

/// The fixture drafter's convolution shape, so the closed form below is checked
/// at the width and grouping the loader actually produces.
const CONV_HIDDEN: usize = SCALE_HIDDEN;
/// Channels sharing one kernel correction, from the fixture's config.
const CONV_GROUP: usize = 16;
/// Corrections per position, per tap.
const CONV_GROUPS: usize = CONV_HIDDEN / CONV_GROUP;
/// Taps this drafter convolves.
const CONV_TAPS: usize = 2;
/// Block positions the closed form covers — enough that a tap reaching before
/// the block and a tap reaching inside it both occur.
const CONV_LEN: usize = 3;

/// The block this section convolves, `x[t][c]`, distinct in both axes.
fn conv_x() -> Vec<f32> {
    (0..CONV_LEN * CONV_HIDDEN)
        .map(|i| (i as f32) * 0.125 - 6.0)
        .collect()
}

/// `base[side][tap][channel]`, distinct in all three axes: reading the wrong
/// side, the wrong tap or the wrong channel gives a different answer.
fn conv_base() -> Vec<f32> {
    (0..2 * CONV_TAPS * CONV_HIDDEN)
        .map(|i| 0.5 - (i as f32) * 0.01)
        .collect()
}

/// One side of [`conv_base`], `[tap][channel]`.
#[allow(
    clippy::indexing_slicing,
    reason = "test fixture: every buffer is sized from the same constants the index is computed from, so an out-of-range index is the harness failing"
)]
fn base_side(base: &[f32], side: usize) -> Vec<f32> {
    base[side * CONV_TAPS * CONV_HIDDEN..(side + 1) * CONV_TAPS * CONV_HIDDEN].to_vec()
}

/// `correction[t][tap][group]`, distinct in all three axes.
fn conv_correction() -> Vec<f32> {
    (0..CONV_LEN * CONV_TAPS * CONV_GROUPS)
        .map(|i| ((i % 7) as f32) * 0.25 - 0.75 + (i as f32) * 0.03)
        .collect()
}

/// The closed form this section checks against:
/// `out[t][c] = SUM_k (base[k][c] + correction[t][k][c / group]) * x[t - k][c]`,
/// with `x[-1] = 0`.
///
/// `base` is one side, `[tap][channel]`; `correction` is `[t][tap][group]`.
#[allow(
    clippy::indexing_slicing,
    reason = "test fixture: every buffer is sized from the same constants the index is computed from, so an out-of-range index is the harness failing"
)]
fn expected_convolution(base: &[f32], correction: &[f32], x: &[f32]) -> Vec<f32> {
    let mut out = vec![0.0f32; CONV_LEN * CONV_HIDDEN];
    for t in 0..CONV_LEN {
        for c in 0..CONV_HIDDEN {
            let mut acc = 0.0;
            for tap in 0..CONV_TAPS {
                if tap > t {
                    continue;
                }
                let k = base[tap * CONV_HIDDEN + c]
                    + correction[(t * CONV_TAPS + tap) * CONV_GROUPS + c / CONV_GROUP];
                acc += k * x[(t - tap) * CONV_HIDDEN + c];
            }
            out[t * CONV_HIDDEN + c] = acc;
        }
    }
    out
}

/// A convolution carrying the given base kernel and projection weight.
fn conv_with(base: &[f32], projection: &[f32]) -> DFlash2Conv {
    let rows = (2 * CONV_TAPS * CONV_GROUPS) as i32;
    DFlash2Conv {
        base_kernel: f32_array(base, &[2, CONV_TAPS as i32, CONV_HIDDEN as i32]),
        kernel_projection: Linear::Plain {
            weight: f32_array(projection, &[rows, CONV_HIDDEN as i32]),
        },
    }
}

fn conv_x_array(x: &[f32]) -> Array {
    f32_array(x, &[1, CONV_LEN as i32, CONV_HIDDEN as i32])
}

fn correction_array(correction: &[f32]) -> Array {
    f32_array(
        correction,
        &[1, CONV_LEN as i32, CONV_TAPS as i32, CONV_GROUPS as i32],
    )
}

/// Tap 0 multiplies this position, tap 1 the one before it, and the tap that
/// reaches before the block reads zero rather than wrapping to its end.
///
/// The correction is zero here, so only the per-channel base term is in play,
/// and each side is checked against its own half of the base kernel — a port
/// reading the other side fails the other assertion.
#[test]
fn a_two_tap_convolution_reads_this_position_and_the_one_before_it() {
    let (drafter, _dir) = scale_drafter(None);
    let base = conv_base();
    let x = conv_x();
    let zero_correction = vec![0.0f32; CONV_LEN * CONV_TAPS * CONV_GROUPS];
    let conv = conv_with(&base, &vec![0.0; 2 * CONV_TAPS * CONV_GROUPS * CONV_HIDDEN]);
    let correction = correction_array(&zero_correction);

    for side in [ConvSide::Prepare, ConvSide::Finish] {
        let got = match drafter.convolve(&conv, &conv_x_array(&x), &correction, side) {
            Ok(a) => a,
            Err(e) => panic!("convolve: {e}"),
        };
        assert_eq!(got.shape(), vec![1, CONV_LEN as i32, CONV_HIDDEN as i32]);
        let want = expected_convolution(&base_side(&base, side as usize), &zero_correction, &x);
        let diff = max_abs_diff(&got, &f32_array(&want, &got.shape()));
        assert!(diff < 1e-4, "side {} differs by {diff}", side as i32);
    }
}

/// The base term is per channel and the correction per group: every channel of
/// one group takes the same correction, and no group takes another's.
#[test]
fn the_kernel_correction_is_shared_across_a_group_of_channels() {
    let (drafter, _dir) = scale_drafter(None);
    let base = conv_base();
    let x = conv_x();
    let correction = conv_correction();
    let conv = conv_with(&base, &vec![0.0; 2 * CONV_TAPS * CONV_GROUPS * CONV_HIDDEN]);

    let got = match drafter.convolve(
        &conv,
        &conv_x_array(&x),
        &correction_array(&correction),
        ConvSide::Prepare,
    ) {
        Ok(a) => a,
        Err(e) => panic!("convolve: {e}"),
    };
    let want = expected_convolution(&base_side(&base, 0), &correction, &x);
    let diff = max_abs_diff(&got, &f32_array(&want, &got.shape()));
    assert!(diff < 1e-4, "the grouped correction differs by {diff}");
}

/// The kernel projection reads the sublayer's input once and its output is laid
/// out `[side, tap, group]`: the prepare side is applied here and the finish
/// side is handed back for the sublayer's output.
#[test]
#[allow(
    clippy::indexing_slicing,
    reason = "test fixture: every buffer is sized from the same constants the index is computed from, so an out-of-range index is the harness failing"
)]
fn one_projection_of_the_input_carries_both_sides_of_the_kernel() {
    let (drafter, _dir) = scale_drafter(None);
    let x = conv_x();
    let rows = 2 * CONV_TAPS * CONV_GROUPS;
    // Row r reads channel 0 only, scaled by r + 1 — so the projection output at
    // position t is (1..=rows) * x[t][0] and every slot of it is distinct.
    let mut projection = vec![0.0f32; rows * CONV_HIDDEN];
    for (r, row) in projection.chunks_exact_mut(CONV_HIDDEN).enumerate() {
        row[0] = (r + 1) as f32;
    }
    let conv = conv_with(&vec![0.0; 2 * CONV_TAPS * CONV_HIDDEN], &projection);

    let (prepared, finish) = match drafter.conv_prepare(&conv, &conv_x_array(&x)) {
        Ok(v) => v,
        Err(e) => panic!("conv_prepare: {e}"),
    };

    // What each side's correction must be, if the projection output is read as
    // [side, tap, group] in that order.
    let side_correction = |side: usize| -> Vec<f32> {
        let mut out = vec![0.0f32; CONV_LEN * CONV_TAPS * CONV_GROUPS];
        for t in 0..CONV_LEN {
            for tap in 0..CONV_TAPS {
                for group in 0..CONV_GROUPS {
                    let slot = side * CONV_TAPS * CONV_GROUPS + tap * CONV_GROUPS + group;
                    out[(t * CONV_TAPS + tap) * CONV_GROUPS + group] =
                        (slot + 1) as f32 * x[t * CONV_HIDDEN];
                }
            }
        }
        out
    };

    assert_eq!(
        finish.shape(),
        vec![1, CONV_LEN as i32, CONV_TAPS as i32, CONV_GROUPS as i32],
        "the finish kernel keeps the [taps, groups] shape the convolution reads"
    );
    let want_finish = side_correction(1);
    let finish_diff = max_abs_diff(&finish, &f32_array(&want_finish, &finish.shape()));
    assert!(
        finish_diff < 1e-2,
        "the finish side must be the projection's second half, off by {finish_diff}"
    );

    let want_prepared =
        expected_convolution(&vec![0.0; CONV_TAPS * CONV_HIDDEN], &side_correction(0), &x);
    let prepared_diff = max_abs_diff(&prepared, &f32_array(&want_prepared, &prepared.shape()));
    assert!(
        prepared_diff < 1e-2,
        "the prepared input must use the projection's first half, off by {prepared_diff}"
    );
}

// ---------------------------------------------------------------------------
// the whole stack, against the reference implementation
// ---------------------------------------------------------------------------

/// The three reference cases are far enough apart that matching all of them is
/// not something a forward ignoring the window or the context could do.
///
/// Without this the parity assertions below could all hold on a port that
/// silently dropped the sliding window, because the fixture would not be able
/// to tell.
#[test]
fn the_reference_cases_are_further_apart_than_the_tolerance() {
    let file = reference_file();
    let cases = ["hidden_wide", "hidden_window_trims", "hidden_short_context"];
    for (i, a) in cases.iter().enumerate() {
        for b in cases.iter().skip(i + 1) {
            let diff = max_abs_diff(&fixture_tensor(&file, a), &fixture_tensor(&file, b));
            assert!(
                diff > REFERENCE_TOL * 5.0,
                "{a} and {b} differ by only {diff}; a fixture this close cannot \
                 separate a port that ignores the window from one that does not"
            );
        }
    }
}

/// The whole stack reproduces the reference forward: the conditioning
/// projection, both convolutions per layer, attention over context and block,
/// RoPE, the MLP and the final norm.
#[test]
fn the_stack_reproduces_the_reference_forward() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden");
    let (drafter, _dir) = scale_drafter(None);

    let got = match drafter.forward_hidden(&block, &ctx) {
        Ok(a) => a,
        Err(e) => panic!("forward_hidden: {e}"),
    };
    let want = fixture_tensor(&file, "hidden_wide");
    assert_eq!(got.shape(), want.shape());
    let diff = max_abs_diff(&got, &want);
    assert!(
        diff <= REFERENCE_TOL,
        "the stack differs from the reference by {diff}"
    );
}

/// Conditioning rows older than the attention window are dropped, and the rows
/// that survive are masked exactly as far back as the window reaches.
///
/// At window 4 over 6 conditioning rows the reference keeps 3 and masks one
/// more of them per block position; a port that kept all 6, or kept 3 and
/// masked none, lands 0.6 away.
#[test]
fn the_window_drops_the_conditioning_rows_the_reference_drops() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden");
    let (drafter, _dir) = scale_drafter(Some(4));

    let got = match drafter.forward_hidden(&block, &ctx) {
        Ok(a) => a,
        Err(e) => panic!("forward_hidden: {e}"),
    };
    let diff = max_abs_diff(&got, &fixture_tensor(&file, "hidden_window_trims"));
    assert!(
        diff <= REFERENCE_TOL,
        "the windowed stack differs from the reference by {diff}"
    );
}

/// A conditioning context shorter than the block is the reference's answer too:
/// nothing in the mask or the position arithmetic assumes the context is the
/// longer of the two.
#[test]
fn a_context_shorter_than_the_block_matches_the_reference() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden_short");
    let (drafter, _dir) = scale_drafter(None);

    let got = match drafter.forward_hidden(&block, &ctx) {
        Ok(a) => a,
        Err(e) => panic!("forward_hidden: {e}"),
    };
    let diff = max_abs_diff(&got, &fixture_tensor(&file, "hidden_short_context"));
    assert!(
        diff <= REFERENCE_TOL,
        "a short context differs from the reference by {diff}"
    );
}

/// An input at a shape the config does not predict is refused, naming the input
/// and what was wanted.
#[test]
fn an_input_the_config_does_not_predict_is_refused() {
    let file = reference_file();
    let block = fixture_tensor(&file, "block_hidden");
    let ctx = fixture_tensor(&file, "target_hidden");
    let (drafter, _dir) = scale_drafter(None);

    // The conditioning is as wide as one target layer, not all of them — what a
    // caller that forgot to concatenate produces.
    let one_layer = match ctx.slice(&[0, 0, 0], &[1, 6, 64], &[1, 1, 1], Device::Cpu) {
        Ok(a) => a,
        Err(e) => panic!("slice: {e}"),
    };
    let err = match drafter.forward_hidden(&block, &one_layer) {
        Ok(_) => panic!("a conditioning input one layer wide must be refused"),
        Err(e) => e.to_string(),
    };
    assert!(
        err.contains("target_hidden") && err.contains("128"),
        "the refusal must name the input and the width it wanted: {err}"
    );

    // A block with no batch axis is the other shape a caller gets wrong.
    let rank_two = match block.reshape(&[4, 64], Device::Cpu) {
        Ok(a) => a,
        Err(e) => panic!("reshape: {e}"),
    };
    let err = match drafter.forward_hidden(&rank_two, &ctx) {
        Ok(_) => panic!("a rank-2 block must be refused"),
        Err(e) => e.to_string(),
    };
    assert!(
        err.contains("block") && err.contains("rank-3"),
        "the refusal must name the input and the rank it wanted: {err}"
    );
}
