//! A9 — Chat-template HF round-trip fixture tests.
//!
//! For each fixture JSON in `tests/chat_template_fixtures/`, this test:
//! 1. Checks whether the snapshot directory named in the fixture exists locally.

//! 2. Loads `chat_template.jinja` from the snapshot via `load_template_source`.
//! 3. Renders with rMLX `ChatTemplate` using the fixture's messages, tools,

//! 4. Asserts `rendered.text == fixture.expected` BYTE-FOR-BYTE.
//!
//! The fixture files are generated by `gen_fixtures.py` using HF transformers
//! as the oracle. Any mismatch is a real rMLX render bug — the assert is
//! never weakened.
//!
//! Archs covered (as of A9):
//! - Qwen3_5MoeForConditionalGeneration (incl. tools, A5 path)
//! - Gemma4ForConditionalGeneration
//! - Gemma3ForConditionalGeneration
//! - Qwen3ForCausalLM (incl. tools)
//! - Qwen2ForCausalLM
//!
//! Mistral / Llama3: deferred — no local snapshot available.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::print_stdout,
    clippy::print_stderr,
    clippy::unreachable,
    clippy::todo,
    clippy::unimplemented,
    clippy::items_after_statements,
    clippy::manual_let_else
)]

use std::path::{Path, PathBuf};

use rmlx_server::chat_template::{load_template_source, ChatMessageTpl, ChatTemplate, RenderOpts};

// ── Fixture type ──────────────────────────────────────────────────────────────

#[derive(serde::Deserialize, Debug)]
struct Fixture {
    snapshot: String,
    // arch is present in the JSON for documentation purposes; not used at runtime.
    #[allow(dead_code)]
    arch: String,
    messages: Vec<FixtureMessage>,
    tools: Option<Vec<serde_json::Value>>,
    add_generation_prompt: bool,
    bos_token: String,
    eos_token: String,
    expected: String,
}

#[derive(serde::Deserialize, Debug)]
struct FixtureMessage {
    role: String,
    content: String,
}

// ── Helpers ────────────────────────────────────────────────────────────────────

fn fixture_dir() -> PathBuf {
    // `tests/chat_template_fixtures/` lives next to this file.
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("chat_template_fixtures")
}

fn o_models_root() -> PathBuf {
    std::env::var_os("RMLX_O_MODELS_ROOT").map_or_else(|| PathBuf::from("models"), PathBuf::from)
}

/// Load a single fixture from the fixtures directory by filename stem.
fn load_fixture(stem: &str) -> Fixture {
    let path = fixture_dir().join(format!("{stem}.json"));
    let data = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read fixture {stem}.json: {e}"));
    serde_json::from_str(&data).unwrap_or_else(|e| panic!("cannot parse fixture {stem}.json: {e}"))
}

/// Run a single round-trip assertion.
///
/// Returns `true` if the test ran, `false` if the snapshot was absent (skip).
fn run_fixture(stem: &str) -> bool {
    let fixture = load_fixture(stem);
    let snap_dir = o_models_root().join(&fixture.snapshot);

    if !snap_dir.exists() {
        eprintln!("[SKIP] {stem}: snapshot '{}' absent", snap_dir.display());
        return false;
    }

    // Some snapshots (e.g. ReaderLM-v2) embed the template in tokenizer_config.json
    // rather than a separate chat_template.jinja. rMLX currently requires the
    // .jinja file; skip gracefully when it's absent rather than panicking.
    let source = if let Ok(s) = load_template_source(&snap_dir) {
        s
    } else {
        eprintln!(
            "[SKIP] {stem}: snapshot '{}' has no chat_template.jinja",
            snap_dir.display()
        );
        return false;
    };
    let tpl = ChatTemplate::new(source)
        .unwrap_or_else(|e| panic!("{stem}: cannot compile template: {e}"));

    let msgs: Vec<ChatMessageTpl<'_>> = fixture
        .messages
        .iter()
        .map(|m| ChatMessageTpl {
            role: m.role.as_str(),
            content: m.content.as_str(),
            ..Default::default()
        })
        .collect();

    let empty_tools: Vec<serde_json::Value> = vec![];
    let tools_slice = fixture.tools.as_deref().unwrap_or(&empty_tools);

    let opts = RenderOpts {
        bos_token: fixture.bos_token.as_str(),
        eos_token: fixture.eos_token.as_str(),
        add_generation_prompt: fixture.add_generation_prompt,
        tools: tools_slice,
        enable_thinking: None,
    };

    let rendered = tpl
        .render(&msgs, &opts)
        .unwrap_or_else(|e| panic!("{stem}: render failed: {e}"));

    assert_eq!(
        rendered.text, fixture.expected,
        "{stem} render diverges from HF reference.\n  got:      {:?}\n  expected: {:?}",
        rendered.text, fixture.expected,
    );

    true
}

// ── Tests — one per fixture ────────────────────────────────────────────────────

#[test]
fn roundtrip_qwen3_5moe_basic() {
    run_fixture("qwen3_5moe_basic");
}

#[test]
fn roundtrip_qwen3_5moe_tools() {
    // A5 tools-injection path — highest-value new coverage.
    run_fixture("qwen3_5moe_tools");
}

#[test]
fn roundtrip_qwen3_5moe_system() {
    run_fixture("qwen3_5moe_system");
}

#[test]
fn roundtrip_gemma4_no_system() {
    run_fixture("gemma4_no_system");
}

#[test]
fn roundtrip_gemma4_multi_turn() {
    run_fixture("gemma4_multi_turn");
}

#[test]
fn roundtrip_gemma3_basic() {
    run_fixture("gemma3_basic");
}

#[test]
fn roundtrip_qwen3_basic() {
    run_fixture("qwen3_basic");
}

#[test]
fn roundtrip_qwen3_tools() {
    run_fixture("qwen3_tools");
}

#[test]
fn roundtrip_qwen2_basic() {
    run_fixture("qwen2_basic");
}
